### ISSUE TITLE
slick-migration-api not resolving

### ISSUE THREAD

**Issue by pkalmakis** [lastland/play-slick-forklift-example#1]
I cloned this example and attempted to run `sbt mg init`, but sbt was unable to resolve `slick-migration-api`.

```
sbt.ResolveException: unresolved dependency: io.github.nafg#slick-migration-api_2.11;0.3.0: not found
```

**Comment by lastland** [comment]
@pkalmakis Thanks for reporting this! Can you pull again and see if it works now?

**Comment by pkalmakis** [comment]
All good. Thanks for the speedy fix!

**Comment by BWStearns** [comment]
For anyone running into this issue in their own projects in the future the fix is to add `resolvers += Resolver.bintrayRepo("naftoligug", "maven")` to their settings (like lastland did here https://github.com/lastland/play-slick-forklift-example/commit/18c254e47dd26b2560e3c3f471aa45f8f465551a).
